export const BOOK_TRIP_REQUEST = 'BOOK_TRIP_REQUEST'
export const BOOK_TRIP_SUCCESS = 'BOOK_TRIP_SUCCESS';
export const BOOK_TRIP_FAILURE = 'BOOK_TRIP_FAILURE';

export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';