export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

export const LOGOUT = 'LOGOUT';

export const BOOK_TRIP_REQUEST = 'BOOK_TRIP_REQUEST';
export const BOOK_TRIP_SUCCESS = 'BOOK_TRIP_SUCCESS';
export const BOOK_TRIP_FAILURE = 'BOOK_TRIP_FAILURE';

export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';

export const ADD_RECENT_SEARCH = 'ADD_RECENT_SEARCH';
export const REMOVE_RECENT_SEARCH = 'REMOVE_RECENT_SEARCH';